### ISSUE TITLE
Data set inconsistency

### ISSUE THREAD

**Issue by SuperXxts** [Ben93kie/SeaDronesSee#11]
The official website（https://seadronessee.cs.uni-tuebingen.de/） mentioned that there were 5630 pictures in the training set of target detection tasks, but in the public data set（https://cloud.cs.uni-tuebingen.de/index.php/s/pNqRDqtLjXbEqDm）, I only found 2975 pictures . There are five categories mentioned in the paper, namely: swimmer, float, swimmer on boat, float on 
 boat, boat, but there are six categories in the data set? So how many categories should there be?

**Comment by Ben93kie** [comment]
The webpage had a typo, we fixed that. Thanks!

In the original SeaDronesSee dataset we feature the following classes:

**swimmer, swimmer on boat, floater, floater on boat, life jacket, boat.**

In the synthetic counterpart (DGTAV-SeaDronesSee) we only feature the following classes:

**swimmer, swimmer on boat, floater, floater on boat, boat.** 

Maybe you mean the synthetic dataset?

**Comment by Ben93kie** [comment]
Closed because of inactivity. Reopen if some issue persists.

**Comment by FraCamp** [comment]
Hi @Ben93kie (good job btw), in the SeaDronesSee.yaml you mention 6 different classes,  which are different from the SDS paper:
yaml -> names: [ 'ignored', 'swimmer', 'boat', 'jetski', 'life_saving_appliances', 'buoy']
while paper :  ['swimmer', 'swimmer on boat', 'floater', 'floater on boat', 'life jacket', 'boat']
Can you please explain better these difference, and what version is used in the pretrained_model_on_SeaDronesSee_ObjectDetection_V2.pt

**Comment by C-der-Baum** [comment]
Hi, thanks @FraCamp!
There are two versions of SeaDronesSee: 

1. The original SeaDronesSee Object Detection Dataset
2. The updated version SeaDronesSee Object Detection v2 introduced in the MaCVi workshop (read here https://openaccess.thecvf.com/content/WACV2023W/MaCVi/html/Kiefer_1st_Workshop_on_Maritime_Computer_Vision_MaCVi_2023_Challenge_Results_WACVW_2023_paper.html)

The latter version has different classes, namely  [ 'ignored', 'swimmer', 'boat', 'jetski', 'life_saving_appliances', 'buoy']. The object detector in this repository was trained on this dataset.

Does that answer your question?
