### ISSUE TITLE
How to download dataset with Linux terminal?

### ISSUE THREAD

**Issue by Kyfafyd** [Ben93kie/SeaDronesSee#15]
Dear author, thanks for the dataset, I would like to learn how to download dataset with Linux terminal.

**Comment by Ben93kie** [comment]
You can use 

`wget https://cloud.cs.uni-tuebingen.de/index.php/s/pNqRDqtLjXbEqDm/download`

to download the whole SeaDronesSee Object Detection dataset. To download individual files, you have to adapt the link.

**Comment by arpita8** [comment]
Dear Author, I tried downloading using Wget, but that doesn't seem to work, so can you please provide some details, I just want to download uncompressed test data. Thank you

**Comment by Ben93kie** [comment]
It works for Object Detection (v1). For Object Detection v2 it does not work for me either. For the Uncompressed Version of Object Detection v2 try:

`wget https://cloud.cs.uni-tuebingen.de/index.php/s/eGNA6YJ89RdQbfX/download`

**Comment by arpita8** [comment]
It doesn't work either, any suggestions on how can I download it?

**Comment by Ben93kie** [comment]
Hmh weird, It works for me.
You could try to download the compressed version via

wget https://cloud.cs.uni-tuebingen.de/index.php/s/nPQbgjiQ6ZqY8fw/download

Does that work?
