### ISSUE TITLE
Leader board upload fail

### ISSUE THREAD

**Issue by euiik** [Ben93kie/SeaDronesSee#21]
hello.
I am trying to upload a json file to "Object detection v2".
However, the "Upload option will open soon" message pops up and the upload fails.

**Comment by Ben93kie** [comment]
Hi!
The error message was still an artifact, thanks for pointing out.
Uploading is possible and now a different error message should pop up. However, the error message is not indicative of the precise format error you caused.
Please re-check whether the format of your json is correct with the proper image names etc.
Let me know if the error persists.
Thanks!
