### ISSUE TITLE
Downloading dataset very slowly

### ISSUE THREAD

**Issue by Italian-PAO** [Ben93kie/SeaDronesSee#22]
MOT dataset is 300+ GB and I am suffering from the poor downloading speed of nextcloud. Cloud you please upload the dataset to google drive? And a compressed version may be perfect for downloading. Thanks a lot!

**Comment by Ben93kie** [comment]
Unfortunately, uploading to Google Drive is not possible at the moment.
But, I'm uploading a jpg-compressed version currently. You can find it under the same link. Note that the uploading process may take another 2-3 hours until it's finished. 

Lastly, you need to change the image names in the corresponding json-annotations from .png to .jpg.

Is that fine?

**Comment by Italian-PAO** [comment]
Thank you so much for your effort!
