### ISSUE TITLE
Downloading the dataset

### ISSUE THREAD

**Issue by arpita8** [Ben93kie/SeaDronesSee#23]
Dear Author, I tried downloading using Wget, and CURL for object detectionV2 but that doesn't seem to work, so can you please provide some details, I just want to download uncompressed test data. Thank you

**Comment by Ben93kie** [comment]
For the Uncompressed Version of Object Detection v2 try:

wget https://cloud.cs.uni-tuebingen.de/index.php/s/eGNA6YJ89RdQbfX/download

It works for me. I don't know why it does not work for you.
You could try to download the compressed version via

wget https://cloud.cs.uni-tuebingen.de/index.php/s/nPQbgjiQ6ZqY8fw/download

Does that work?
