### ISSUE TITLE
resource is invalid

### ISSUE THREAD

**Issue by AgSword** [Ben93kie/SeaDronesSee#26]
Dear Author, i want to download pictures in Multi Object Tracking to get dataset about single object tracking,but the resource is invalid

**Comment by Ben93kie** [comment]
Hi,
sorry for the inconvenience. The link expired. We created a new one, that can also be seen on the webpage:
https://cloud.cs.uni-tuebingen.de/index.php/s/X7E4toBJsjAXCTK

**Comment by AgSword** [comment]
Thank you very much and pay tribute to your work!

**Comment by Ben93kie** [comment]
Thanks!
