### ISSUE TITLE
Is SOT dataset the same as MOT dataset？

### ISSUE THREAD

**Issue by jackydinosaur** [Ben93kie/SeaDronesSee#27]
Hello, thanks for the great work!!
May I confirm with you that  SOT dataset is the same as MOT dataset？
In README.md：
**_You find the corresponding frames that need to be taken from the Multi-Object Tracking link._**
Does it mean that SOT dataset and MOT dataset are the same？

I am looking forward to your reply.

**Comment by Ben93kie** [comment]
Hi, thanks for your interest!
The frames are a subset of MOT. The individual clips are not identical in length to the ones from MOT. But overall, they are based on the same frames.
Does that answer your question?

**Comment by jackydinosaur** [comment]
I see. Thanks for your reply.
