### ISSUE TITLE
What is the difference betwee object detection and object detection v2

### ISSUE THREAD

**Issue by jordan44665** [Ben93kie/SeaDronesSee#30]
I used the object detection data set to run some experiments on my machine but now I see that there is a different leader board for object detection v2 and it has a different data set. What is the difference between the two data sets?

**Comment by Ben93kie** [comment]
As per https://seadronessee.cs.uni-tuebingen.de/wacv23_SeaDronesSee, ODv2 has more images in more diverse environments & scenarios and has different classes. Let me know if you need more info!

**Comment by Ben93kie** [comment]
Inactivity

**Comment by jordan44665** [comment]
Sorry for the delay -- thank you for the information. That should do for now.
