### ISSUE TITLE
Json submission format 

### ISSUE THREAD

**Issue by peng8ling** [Ben93kie/SeaDronesSee#32]
I am sorry to bother you but I have a question about the json format. when I submit result json, I was reminded script execution failed.Make sure the format of your json is correct, but I can't find problems about my uploading files

**Comment by peng8ling** [comment]
[{"image_id": 1, "category_id": 3, "score": 1.0, "bbox": [391.99999999999994, 479.0, 115.0, 111.0]}, {"image_id": 4, "category_id": 3, "score": 1.0, "bbox": [1161.0, 738.0, 70.0, 62.0]}, {"image_id": 8, "category_id": 3, "score": 1.0, "bbox": [95.0, 330.0, 73.0, 126.99999999999999]}, {"image_id": 8, "category_id": 3, "score": 1.0, "bbox": [511.0, 0.0, 71.0, 10.0]}

**Comment by Ben93kie** [comment]
Which track?

**Comment by peng8ling** [comment]
object detection

**Comment by Ben93kie** [comment]
Yes, sorry for the circumstances! We are in the process of restructuring the webserver and extending it. 
In that process, I messed up with the script execution of the Object Detection track.

Now, it should work again. If not, feel free to reopen this issue again.
