### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tcdnm** [Ben93kie/SeaDronesSee#33]
Hi there, under which license has this dataset been released?

**Comment by tarsier-admin** [comment]
Dear authors, thank you for publishing the dataset. I have the same question as above. What is the license of this dataset?

**Comment by soenmezanil** [comment]
Dear authors, thank you for publishing the dataset. I have the same question as above. What is the license of this dataset?

**Comment by Ben93kie** [comment]
Hey!
Sorry for the late reply.
No too familiar with licenses, but I guess something like Creative Commons CC0 1.0 Universal (CC0 1.0) is suitable.
Essentially, you can do whatever with the data as long as you don't hold my accountable for any potentially caused damage or such :)

**Comment by Ben93kie** [comment]
Added that in the README, let me know if any question remains.
