### ISSUE TITLE
JSON2YOLO get error

### ISSUE THREAD

**Issue by xiaohangguo** [Ben93kie/SeaDronesSee#34]
Hello, I downloaded the seadronessee v2 version of the dataset and then I want to convert this COCO dataset into a YOLO dataset

Traceback (most recent call last):
  File "/public/home/lvshuhang/RTDETR-main/JSON2YOLO/general_json2yolo.py", line 387, in <module>
    convert_coco_json('/public/home/lvshuhang/RTDETR-main/CompressedVersion/annotations/',  # directory with *.json
  File "/public/home/lvshuhang/RTDETR-main/JSON2YOLO/general_json2yolo.py", line 279, in convert_coco_json
    if ann['iscrowd']:
KeyError: 'iscrowd'
(JSON2YOLO) [lvshuhang@node75 JSON2YOLO]$ 
KeyError: 'iscrowd'

I'm using a script written by ultralytics, but when executing it, it seems to be blowing up the iscrowd error
This indicates that when processing an annotation in a JSON file, the key 'iscrowd' is not in the dictionary for that annotation.

**Comment by xiaohangguo** [comment]
I tried to modify your code as follows:
```
import json
import argparse
import os

def convertToYolo(x_coco, y_coco, w_coco, h_coco, w_img, h_img):
    x_yolo = (x_coco + w_coco/2) / w_img
    y_yolo = (y_coco + h_coco/2) / h_img
    w_yolo = w_coco / w_img
    h_yolo = h_coco / h_img
    return [x_yolo, y_yolo, w_yolo, h_yolo]

def computeInput(annotationPath, outputPath):
    with open(annotationPath) as CocoFormat:
        data = json.load(CocoFormat)
    
    # Create a dictionary to map image IDs to image data
    image_data = {image['id']: image for image in data['images']}

    for key in data['annotations']:
        image_id = key['image_id']
        if image_id in image_data:
            image = image_data[image_id]
            h_img, w_img = image['height'], image['width']
            yoloFormat = convertToYolo(*key['bbox'], w_img, h_img)
            # Ensure output directory exists
            os.makedirs(outputPath, exist_ok=True)
            file_path = os.path.join(outputPath, f"{image_id}.txt")
            with open(file_path, "a") as f:
                f.write(f"{key['category_id']} {' '.join(map(str, yoloFormat))}\n")


parser = argparse.ArgumentParser()
parser.add_argument('--annotations', type=str, default=None, help='path to the folder which contains the annotation json files')
parser.add_argument('--labels', type=str, default=None, help='path to the YOLOv7 data folder')
parser.add_argument('--val', action='store_true', help='convert the val annotation')
parser.add_argument('--train', action='store_true', help='convert the train annotation')
parser.add_argument('--test', action='store_true', help='convert the test annotation')
options = parser.parse_args()

if not (options.val or options.train or options.test):
    print("Please specify the annotations to convert")
    exit()

if options.val:
    computeInput(os.path.join(options.annotations, "instances_val.json"), os.path.join(options.labels, "val", "labels"))
if options.train:
    computeInput(os.path.join(options.annotations, "instances_train.json"), os.path.join(options.labels, "train", "labels"))
if options.test:
    computeInput(os.path.join(options.annotations, "instances_test.json"), os.path.join(options.labels, "test", "labels"))

print("Conversion Completed")

```
in this way, 
I can train normally, but all the images come out as background, and the label information seems to be wrong, is it because of the ignored tag?

**Comment by Ben93kie** [comment]
Sry, just saw it now.

Yes, the iscrowd field may not be present although expected by some scripts that convert COCO->Yolo. You can just manually add that field to every annotation instance, then it should work out-of-the-box (it's the only different to standard COCO format afaik).

If your predictions all come out as background, you should check the categories that you train on again. There is an ignored class present in the json annotation file, but none of the actual boxes have that category. We explicitly made the regions that we want the OD to ignore black in the image space already. Maybe you can delete the "ignore" category from your categories field in the json?

![image](https://github.com/Ben93kie/SeaDronesSee/assets/64975055/b9d191a3-c7ad-427c-ab73-140a3f0788d6)

**Comment by xiaohangguo** [comment]
> Sry, just saw it now.
> 
> Yes, the iscrowd field may not be present although expected by some scripts that convert COCO->Yolo. You can just manually add that field to every annotation instance, then it should work out-of-the-box (it's the only different to standard COCO format afaik).
> 
> If your predictions all come out as background, you should check the categories that you train on again. There is an ignored class present in the json annotation file, but none of the actual boxes have that category. We explicitly made the regions that we want the OD to ignore black in the image space already. Maybe you can delete the "ignore" category from your categories field in the json?
> 
> ![image](https://private-user-images.githubusercontent.com/64975055/289622232-b9d191a3-c7ad-427c-ab73-140a3f0788d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDc0NTQsIm5iZiI6MTcwMjM0NzE1NCwicGF0aCI6Ii82NDk3NTA1NS8yODk2MjIyMzItYjlkMTkxYTMtYzdhZC00MjdjLWFiNzMtMTQwYTNmMDc4OGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyMTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YmIyNTNhNzQ1Y2NhZTY1YmY1MTIwYWIwMmZkMDNjZGJiMzUxZjJkODA0MjQyODk3YzRhMjdjNWE0ZjU1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TuYhOW2iwrf53R_B9OxvsbzGZ4_H2p6LPFk3ikS3AmU)


Haha, I'm glad to receive your letter. In the end, I still haven't solved the problem, but I found a new method - downloading a dataset from Roboflow. By the way, is this repository your official one?

```
SeaDronesSee ODV2 > rebalanced no tile1230x930
https://universe.roboflow.com/ntnu-2wibj/seadronessee-odv2

Provided by a Roboflow user
License: CC BY 4.0

https://seadronessee.cs.uni-tuebingen.de/dataset
Reference
@inproceedings{varga2022seadronessee,
title={Seadronessee: A maritime benchmark for detecting humans in open water},
author={Varga, Leon Amadeus and Kiefer, Benjamin and Messmer, Martin and Zell, Andreas},
booktitle={Proceedings of the IEEE/CVF Winter Conference on Applications of Computer Vision},
pages={2260--2270},
year={2022} }
```

Additionally, I noticed that the dataset downloaded from the official website does not have a test set, but there is one on Roboflow. If I want to conduct experiments, how should I choose (there are also multiple versions on Roboflow)?"

**Comment by xiaohangguo** [comment]
I am currently using the aforementioned dataset for small object detection experiments, but I am doubtful and troubled about whether this test set can be used. Additionally, I read a paper that used this dataset, but they used the performance on the validation set as the model evaluation metric.

**Comment by Ben93kie** [comment]
That's cool. Didn't know that it exists on Roboflow.

The code if the "official" one, yes. But, it's very sparse only with minimal support only unfortunately.

The test set images are available, but **not** the test set labels. You have to upload your json predictions to our evaluation webserver, then you'll see the results on the leaderboard:

https://macvi.org/

Let me know if you have any issues or questions.

**Comment by xiaohangguo** [comment]
> That's cool. Didn't know that it exists on Roboflow.
> 
> The code if the "official" one, yes. But, it's very sparse only with minimal support only unfortunately.
> 
> The test set images are available, but **not** the test set labels. You have to upload your json predictions to our evaluation webserver, then you'll see the results on the leaderboard:
> 
> https://macvi.org/
> 
> Let me know if you have any issues or questions.

I see, I see, I guess the picture on Roboflow may have been created by a player when he was doing data augmentation, not your "official" work. Then I should go ahead and make changes to your code. Instead of using datasets on the RoboFlow platform. Unfortunately, I've done a lot of experiments on his dataset.But the good news is that if I can solve the previous problem on your dataset and successfully train the model with good results, and upload the json file to your evaluation system, then I should be able to get a "convincing" metric, haha!

**Comment by Ben93kie** [comment]
That sounds like a good plan!

**Comment by xiaohangguo** [comment]
long time no see! I successfully transformed the dataset (JSON2YOLO) and now there is a category 'ignored' which is a black erased block in the image right? Is it necessary to remove all the labeling information from this part?

**Comment by Ben93kie** [comment]
That's great to hear!
Correct, the ignored region annotations refer to the already erased parts of the images.

You could leverage this information (e.g., not computing the loss in this area at all). But for most implementations, you can safely ignore it. So, just remove it from the annotations and you are fine.

**Comment by xiaohangguo** [comment]
Happy New Year, bro!
I will skip the tag info that needs to be ignored and then train. Hopefully I can get good results and then upload the json to your system, wish me luck~!

**Comment by xiaohangguo** [comment]
I've made a new discovery, I've found that there doesn't seem to be any images that actually have an ignore tag present, although they do have an id of 0 in the very first part, but not a tag of 0.

**Comment by Ben93kie** [comment]
That could be. In that case, just ignore the key entirely I guess ;)

Happy New Year!

**Comment by xiaohangguo** [comment]
![5b368adfa4922c31663d113871154a8](https://github.com/Ben93kie/SeaDronesSee/assets/72799392/3c8d7053-a9da-4e89-ba55-cc4717046d91)
:) yes, no 0 and no ignore~! lucky~!

**Comment by xiaohangguo** [comment]
hello, I'm having some problems calculating the COCO review metrics, there is no 'iscrowd' field in the current tag file, I added the value 0 to each tag, and then the calculations give me all 0's, which is strange.

**Comment by Ben93kie** [comment]
I need a bit more information. Where did you evaluate/upload (which competition?). If you properly added the iscrowd field and set it to 0, it should evaluate properly. Are you sure that your predictions are "good"?

**Comment by xiaohangguo** [comment]
1."This is for the Sea Drone V2 Object Detection competition. I'm calculating the validation set scores (offline)."

2."I'm not sure if this prediction is 'good', but it can compute scores on YOLO. I need to save the inference results in JSON format and then compare them with the labels of the validation set for score calculation. Currently, the mAP score calculated by YOLO seems to be working properly, so can I trust that this prediction is 'good'?"

3."By the way, can the scores on the validation set indicate the capability of the model? I have read papers from participants in the Sea Drone V2 Object Detection competition. Their image sizes are quite large, around 2400x2400. Does size affect model training and inference, and what size of images should I use for training to make the results convincing?"

**Comment by Ben93kie** [comment]
If you are calculating them offline, you can compare manually for certain images whether the predictions are good. But, if the YOLO ones are working (yielding good results), then the predictions should be good.
Then I suspect your naming of the images is wrong/does not coincide with the actual image (indices).

Yes, validation set is a good proxy. Generally, the domain gap between train, val, test is not that high in this case. Larger images tend to better just because there are a lot of very small swimmers 20px. Obviously, inference speed is lower in that case. Many people use some kind of tiling approach for training and do inference with the largest possible resolution (whatever you can do based on your latency/GPU requirement).

**Comment by xiaohangguo** [comment]
I've checked, and it seems that the actual image-label files might contain additional information about other images or videos, such as from which .mp4 video they come, etc. This information might be interfering with the calculation.

I have a solution: I can convert the YOLO labels, which I've successfully trained with, back into JSON format. This way, I can obtain a noise-free JSON file.

**Comment by Ben93kie** [comment]
Sounds good
