### ISSUE TITLE
Datasets unavailable as of 12/22/23 in eastern US

### ISSUE THREAD

**Issue by robert-m-taylor** [Ben93kie/SeaDronesSee#35]
None of the datasets are currently available for download.   The dataserver https://cloud.cs.uni-tuebingen.de/ is not accessible in eastern United States as of time of this writing 12/22/23 12:13pm EST.

**Comment by Ben93kie** [comment]
Hi, yes, unfortunately the servers are down in the period 22th Dec afternoon to 27th Dec 8am and 29th Dec afternoon to
2nd Jan 8am. If you let me know which dataset you need, I might be able to reupload it somewhere in the meantime?

**Comment by x33rak** [comment]
@Ben93kie Hi, would it be possible to provide the object detection and object detection v2 datsets?

**Comment by Ben93kie** [comment]
You can find all the datasets on 

https://macvi.org/

I also restarted 

https://seadronessee.cs.uni-tuebingen.de/

where you can also find some of the datasets (eventually linking to the same place).

**Comment by x33rak** [comment]
thank you!

**Comment by bartoszptak** [comment]
@Ben93kie Is the Multi-Object Tracking dataset available?

**Comment by Ben93kie** [comment]
Sry, we had a short update of the server. Now should be available again. Let me know if there are any issues.

**Comment by bartoszptak** [comment]
> Sry, we had a short update of the server. Now should be available again. Let me know if there are any issues.

Yes, the server works fine now.

But I am confused about the `SeaDronesSee_MOT`. Where are ground-truth files for training and validation sequences? How are the JPEG images related to videos?

**Comment by Ben93kie** [comment]
Hmh, sorry the upload must have failed..
I re-uploaded them. Now, you should be able to see them.

Also, have a look here for uploading instruction or how to work with the data and how to upload your predictions:

https://macvi.org/workshop/macvi23/challenges/uav_tracking

Please note that the compressed version are jpgs and not pngs as original (so you have to consider the file ending in the annotation file).

Does that help?
