### ISSUE TITLE
Object Detection DataSet Unavailable

### ISSUE THREAD

**Issue by Polaris-F** [Ben93kie/SeaDronesSee#36]
The dataset for Object Detection located at https://seadronessee.cs.uni-tuebingen.de/dataset is not accessible as of 17:52:21 on June 18, 2024, China Standard Time (CST).

**Comment by Ben93kie** [comment]
Hi!
We highly encourage you to switch to the v2 version of Object Detection (the v1 is a subset thereof).
If you still need it, I can have a look. Just let me know

**Comment by Polaris-F** [comment]
Got it. I will use the v2 version.
